# Generated by Django 5.2.8 on 2025-11-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(db_comment='nombre de la evidencia para su identificacion en carpetas', max_length=100)),
                ('fecha_entrega', models.DateField(blank=True, db_comment='fecha limite de entrega de la evidencia', null=True)),
            ],
            options={
                'db_table': 'archivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carpetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_comment='nombre de la carpeta (ej: plan concertado, evidencias de aprendizaje, guias de aprendizajes,  etc.)', max_length=100)),
            ],
            options={
                'db_table': 'carpetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_comment='que tipo de documento tiene el usuario cedula, tarjeta de identidad, etc', max_length=20)),
                ('numero', models.BigIntegerField(blank=True, db_comment='es el numero de identificacion', null=True)),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciasAprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(db_comment='documentos evidencias, material de apoyo', max_length=50)),
                ('observaciones', models.CharField(blank=True, db_comment=' observaciones del intructor', max_length=300, null=True)),
                ('fecha_entrega', models.DateField(blank=True, db_comment='la fecha de la entrega de las evidencias', null=True)),
            ],
            options={
                'db_table': 'evidencias_aprendiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciasFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'evidencias_ficha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciasInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_comment='titulo de la evidencia que el instructor crea', max_length=70)),
                ('instrucciones', models.CharField(blank=True, db_comment='instrucciones detalladas de la evidencia a entregar', max_length=200, null=True)),
                ('calificacion', models.CharField(db_comment='nota maxima o calificacion asignada a la evidencia', max_length=20)),
                ('fecha_de_entrega', models.DateField(blank=True, db_comment='fecha limite en la que el aprendiz debe entregar la evidencia', null=True)),
                ('archivo', models.CharField(db_comment='nombre o ruta del archivo adjunto correspondiente a la evidencia', max_length=100)),
            ],
            options={
                'db_table': 'evidencias_instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.IntegerField(db_comment='aqui se define a cual ficha pertenece')),
            ],
            options={
                'db_table': 'ficha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaCarpetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ficha_carpetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ficha_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_comment='aqui va si es diurna, nocturna o mixta', max_length=50)),
            ],
            options={
                'db_table': 'jornada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_comment='titulo del material', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_comment='instrucciones o descripcion del material de apoyo', max_length=500, null=True)),
                ('archivo', models.CharField(blank=True, db_comment='nombre o ruta del archivo de apoyo adjunto por el instructor', max_length=255, null=True)),
            ],
            options={
                'db_table': 'material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'material_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NombreAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_comment='aqui va el nombre que se le asigne a la competencia', max_length=200)),
            ],
            options={
                'db_table': 'nombre_asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(db_comment='tecnico o tecnologo', max_length=150)),
            ],
            options={
                'db_table': 'programa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_comment='aqui se define el rol del usuario que son (aprendiz, instructor, coordinacion y observador)', max_length=50)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_comment='Si la competencia es tecnica o transversal', max_length=200)),
            ],
            options={
                'db_table': 'tipo_asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(db_comment='aqui van los nombre del usuario', max_length=100)),
                ('apellidos', models.CharField(db_comment='aqui van los apellidos del usuario', max_length=100)),
                ('correo', models.CharField(db_comment='aqui estara el correo del usuario', max_length=100)),
                ('telefono', models.BigIntegerField(db_comment='aqui va el numero de telefono del usuario')),
                ('usuario', models.CharField(db_comment='aqui va el usuario de regristro de cada uno de los usuarios', max_length=100)),
                ('contrasena', models.CharField(db_comment='aca estara la contrasena para entrar al sistema de cada usuario', max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuario_rol',
                'managed': False,
            },
        ),
    ]
