# Generated by Django 5.2.8 on 2025-12-01 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ficha_asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NombrePrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'nombre_programa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivoInstructorFicha',
            fields=[
                ('idarchivoficha', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='portafolio_instructor/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('carpeta', models.ForeignKey(db_column='idcarpetas', on_delete=django.db.models.deletion.DO_NOTHING, to='pantallas.carpetas')),
                ('ficha', models.ForeignKey(db_column='idficha', on_delete=django.db.models.deletion.DO_NOTHING, to='pantallas.ficha')),
                ('instructor', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to='pantallas.usuario')),
            ],
            options={
                'db_table': 'archivo_instructor_ficha',
                'managed': True,
            },
        ),
    ]
