# Generated by Django 5.2.8 on 2025-11-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ficha_asignatura',
                'managed': False,
            },
        ),
    ]
