# Generated by Django 5.2.8 on 2025-12-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantallas', '0002_fichaasignatura_archivoinstructorficha'),
        ('pantallas', '0002_fichaasignatura_nombreprograma_and_more'),
    ]

    operations = [
    ]
