# Generated by Django 5.2.8 on 2025-12-02 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantallas', '0003_merge_20251202_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NombrePrograma',
        ),
    ]
