# Generated by Django 5.2.8 on 2025-12-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallas', '0004_delete_nombreprograma'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombrePrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'nombre_programa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PortafolioInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(db_comment='trimestre asignado (1-7)')),
                ('titulo_archivo', models.CharField(db_comment='nombre visible del archivo', max_length=150)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='portafolio_instructor/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portafolio_instructor',
                'managed': False,
            },
        ),
    ]
