# Generated by Django 5.2.8 on 2025-12-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallas', '0005_nombreprograma_portafolioinstructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='equipo_ejecutor/')),
                ('nombre_editable', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'archivo_equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarpetaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carpeta_equipo',
                'managed': False,
            },
        ),
    ]
