# Generated by Django 5.2.8 on 2025-12-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantallas', '0006_carpetaequipo_archivoequipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivoequipo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carpetaequipo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': True},
        ),
    ]
